name: Release and Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Build project
        run: npx ng build --configuration production

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  docker_build_and_push:
    name: Package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Build and push Docker image
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          TAGS="latest,$TAG_NAME"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg APP_NAME=hello-world-frontend \
            $(echo $TAGS | tr ',' '\n' | sed 's/^/-t ryuunosukeds3\/hello-world-frontend:/') \
            --push .

  update_raspberry_cluster:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Checkout hello-world-gitops repo
        uses: actions/checkout@v3
        with:
          repository: RyuunosukeDS3/hello-world-gitops
          token: ${{ secrets.RELEASE_TOKEN }}
          path: hello-world-gitops

      - name: Update values with current frontend tag
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          FILE="hello-world-gitops/hello-world/helm/hello-world-values.yaml"

          if ! command -v yq &> /dev/null; then
            echo "Installing yq..."
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

          echo "Updating image.tag to $TAG_NAME in $FILE"
          yq eval ".frontend.image.tag = \"$TAG_NAME\"" -i "$FILE"

          echo "Modified file:"
          cat "$FILE"

      - name: Commit and push changes
        run: |
          cd hello-world-gitops
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hello-world/helm/hello-world-values.yaml
          git commit -m "chore: update hello-world-frontend image tag to $TAG_NAME"
          git push origin main
