name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install
        
      - name: Run linter
        run: npx ng lint

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Build project
        run: npx ng build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t hello-world-backend:latest .
          docker save hello-world-backend:latest -o image.tar

      - name: Upload image.tar
        uses: actions/upload-artifact@v4
        with:
          name: image.tar
          path: .

  test:
    name: Run Tests (Unit + E2E)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Chrome dependencies
        run: |
          curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/google-linux.gpg > /dev/null 
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update 
          sudo apt-get install -y chromium

      - name: Set Puppeteer Executable Path
        run: echo "PUPPETEER_EXECUTABLE_PATH=$(which chromium-browser)" >> $GITHUB_ENV

      - name: Run unit tests with coverage
        run: |
          npx ng test --watch=false --code-coverage --no-progress
        env:
          CI: true

      - name: Upload unit test coverage
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: coverage/lcov.info


      - name: Run E2E tests with Puppeteer
        run: |
          npx npm run e2e:cov
        env:
          CI: true

      - name: Upload e2e test coverage
        uses: actions/upload-artifact@v4
        with:
          name: e2e-coverage
          path: e2e/coverage/lcov.info

  trivy-fs:
    name: Trivy FS Scan (Source Code)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in fs mode
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy plugin install github.com/umax/trivy-plugin-sonarqube
          trivy fs --format=json --output=trivy.json --exit-code=1 --ignore-unfixed=true .
          trivy sonarqube trivy.json > trivy-fs.json

      - name: Upload trivy-fs.json
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs.json
          path: .

  trivy-image:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v3

      - name: Download image.tar
        uses: actions/download-artifact@v4
        with:
          name: image.tar
          path: .

      - name: Load docker image
        run: docker load -i image.tar

      - name: Run Trivy vulnerability scanner in image mode
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy plugin install github.com/umax/trivy-plugin-sonarqube
          trivy image --format=json --output=trivy.json --exit-code=1 --ignore-unfixed=true hello-world-backend:latest
          trivy sonarqube trivy.json > trivy-image.json

      - name: Upload trivy-image.json
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image.json
          path: .

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [test, trivy-fs, trivy-image]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Download unit test coverage
        uses: actions/download-artifact@v4
        with:
          name: unit-coverage
          path: coverage/lcov.info

      - name: Download e2e test coverage
        uses: actions/download-artifact@v4
        with:
          name: e2e-coverage
          path: coverage-e2e/lcov.info

      - name: Upload trivy-fs.json
        uses: actions/download-artifact@v4
        with:
          name: trivy-fs.json
          path: .

      - name: Upload trivy-image.json
        uses: actions/download-artifact@v4
        with:
          name: trivy-image.json
          path: .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
